sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD) # GETS THE LATEST SHAT FROM GIT e.g. git checkout SHA
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1 # ENSURE YOU GET NO PROMPT WHEN INSTALLING google sdk 
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-302508 # next 3 commands should be run in the gcloud as well
  - gcloud config ser compute/zone asia-east1-a
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t eefth/react-test -f ./client/Dockerfile.dev

script:
  - docker run eefth/react-test npm test -- --coverage
 
deploy:
  provide: script
  script: bash ./deploy.sh
  on:
    branch: master 